permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: GarfieldEr007
  link: https://garfielder007.github.io
  
  #<!--
  #email: lay.1010@hotmail.com
   #weibo: http://weibo.com/orangeissweet
  #-->
  
  github: https://garfielder007.github.io
  
  #<!--
  #music: http://site.douban.com/linanya
  #linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232
  #-->

# 站点信息
title: GarfieldEr007
description: My personal blog
url: garfielder007.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/garfielder007_avatar.png
favicon: /public/img/garfielder007_avatar.png
# google analytics 设置
ga:
  id: UA-54262064-1 
  url: garfielder007.github.io

# disqus 设置
disqus:
  shortname: GarfieldEr007

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档